### ISSUE TITLE
config 被重置

### ISSUE THREAD

**Issue by guansss** [umijs/umi-presets-pro#9]
proconfig 插件把 userConfig 中有定义的属性全部重置到了初始状态，导致其他插件的修改无效

ref: https://github.com/umijs/umi/issues/9211

https://github.com/umijs/umi-presets-pro/blob/72eb8ed2615e4273330e8e4ad2fcb0bf6a6be28f/packages/umi-preset-pro/src/features/proconfig.ts#L6-L19

**Comment by chenshuai2144** [comment]
你这个pr的地址不大对吧

**Comment by guansss** [comment]
啊这，怎么开到那边去了
